services:

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
      - backend_media:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3003,http://127.0.0.1:3003
      - CSRF_TRUSTED_ORIGINS=http://localhost:3003,http://127.0.0.1:3003
    command: >
      sh -c "python manage.py migrate --run-syncdb &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  backend_media:
