# Generated by Django 6.0

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0010_guest_scheduled_send_claimed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RsvpWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('auto_send_pass', models.BooleanField(default=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rsvp_workflows', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_workflow', to='guests.event')),
                ('invitation_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rsvp_invitation_workflows', to='guests.whatsapptemplate')),
                ('pass_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rsvp_pass_workflows', to='guests.whatsapptemplate')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='RsvpRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('response_status', models.CharField(choices=[('awaiting', 'Awaiting response'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], db_index=True, default='awaiting', max_length=20)),
                ('invitation_status', models.CharField(choices=[('not_sent', 'Not sent'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='not_sent', max_length=20)),
                ('pass_status', models.CharField(choices=[('held', 'Held'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('not_issued', 'Not issued')], db_index=True, default='held', max_length=20)),
                ('invitation_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('pass_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('pass_queued_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_recipients', to='guests.guest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='rsvp.rsvpworkflow')),
            ],
            options={'ordering': ['guest__full_name']},
        ),
        migrations.CreateModel(
            name='RsvpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('source', models.CharField(choices=[('web', 'RSVP page'), ('whatsapp', 'WhatsApp button')], default='web', max_length=20)),
                ('sender_phone', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rsvp.rsvprecipient')),
            ],
            options={'ordering': ['-received_at']},
        ),
        migrations.AddConstraint(
            model_name='rsvprecipient',
            constraint=models.UniqueConstraint(fields=('workflow', 'guest'), name='unique_rsvp_recipient_per_workflow'),
        ),
    ]
