# Generated by Django 6.0.5 on 2026-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_bg_color',
            field=models.CharField(blank=True, default='none', max_length=20),
        ),
    ]
