# Generated by Django 6.0.5 on 2026-06-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_event_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, help_text='WhatsApp template to use for this event. Falls back to the global default if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='guests.whatsapptemplate'),
        ),
    ]
