# Generated by Django 6.0.5 on 2026-06-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_event_whatsapp_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Template body text with {{1}}, {{2}} placeholders — used for preview only'),
        ),
    ]
