# Generated by Django 6.0.5 on 2026-06-21 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_whatsapptemplate_body_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'template categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='whatsapptemplate',
            options={'ordering': ['category__name', 'display_name', 'name']},
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category for grouping templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='guests.templatecategory'),
        ),
    ]
