# Generated by Django 6.0.5 on 2026-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_templatecategory_and_template_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='scheduled_send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
