# Generated by Django 6.0.5 on 2026-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_guest_scheduled_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='scheduled_send_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
