# Generated by Django 6.0 on 2026-09-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0020_named_plus_one_and_rsvp_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='What this part of the event is called, e.g. "Church Ceremony".',
                        max_length=120,
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        help_text="Where this part of the event happens.",
                        max_length=255,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="Full date and time this part of the event begins."
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text='Optional guest-facing detail, e.g. "Strictly white attire".',
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="guests.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "starts_at", "id"],
            },
        ),
    ]
